ALTER TABLE listing_images
  ADD COLUMN IF NOT EXISTS width INTEGER,
  ADD COLUMN IF NOT EXISTS height INTEGER,
  ADD COLUMN IF NOT EXISTS ai_mime_type TEXT,
  ADD COLUMN IF NOT EXISTS ai_image_bytes BYTEA,
  ADD COLUMN IF NOT EXISTS preview_mime_type TEXT,
  ADD COLUMN IF NOT EXISTS preview_image_bytes BYTEA,
  ADD COLUMN IF NOT EXISTS preview_width INTEGER,
  ADD COLUMN IF NOT EXISTS preview_height INTEGER;

